### ISSUE TITLE
请问您的nginx里配置是如何的？

### ISSUE THREAD

**Issue by anyforever** [leongpeng/docker#1]
目前搭好之后，发现各个容器能正常启动，nginx访问静态页，也能正常，不过不能正常发送给php的fast-fpm，这样PHP的页面是无法正常解析的。

想请教下您的nginx配置是如何发送给php cgi的。

我试了以下两种方式，都不能正常解析

1.nginx下，server段内

location ~ .*\.php$
		{
			fastcgi_pass 127.0.0.1:9000;
			fastcgi_index index.php;
			include fcgi.conf;
		}
php的yaml配置将配置9000映射到容器的9000端口

2.nginx下改为：
fastcgi_pass php:9000;  //php为php的容器名

yaml配置不做php端口转发

以上两种均未能正常使用php

**Comment by leepin** [comment]
server {
  listen 80;
  server_name domain.com;
  index index.html index.htm index.php;
  root /app/application;
  
  location ~ \.php$ {
    fastcgi_pass   php:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    include        fastcgi_params;
  }

  location ~ /\.ht {
    deny  all;
  }

  access_log off;
}

**Comment by anyforever** [comment]
好的，谢谢，我试下去。

**Comment by leongpeng** [comment]
1. clone 下来的目录里面的 App 里有默认配置文件
2. 和正常的是一样的改 app 目录下的配置文件，改完过后需要重启 docker 容器。
3. 返回502 是你后段配置问题，你 tcping 一下 php 的 9000 端口是否正常 `tcping php 9000`

**Comment by anyforever** [comment]
@leongpeng 
嗯，3Q
找到问题了。我PHP配置里监控最127.0.0.1的9000端口的问题。收不到nginx docker发过去的
